### ISSUE TITLE
How can I specify the source of the .git folder?

### ISSUE THREAD

**Issue by UmNiK7** [typicode/husky-4-to-5#11]
My .git folder is not in the same folder as the package.json.
During installation - the husky does not find the .git folder and gives an error.
Could you add an additional flag where I can specified my .git folder source.

The structure of my project:
```
    .git
    server
    client
        package.json
```

**Comment by typicode** [comment]
Hi @UmNiK7,

Personally, for this particular case, I'd do it manually and follow https://typicode.github.io/husky/#/?id=manual and https://typicode.github.io/husky/#/?id=custom-directory
