### ISSUE TITLE
Fails if using zsh shell

### ISSUE THREAD

**Issue by eschaefer** [typicode/husky-4-to-5#3]
Using OS X Catalina...

```
$ npx github:typicode/husky-4-to-5#main --package-manager yarn
zsh: no matches found: github:typicode/husky-4-to-5#main
```

**Comment by typicode** [comment]
What's your version of `npx`?

**Comment by josokinas** [comment]
Same issue, using zsh and npx v7.5.2.

**Comment by eschaefer** [comment]
@typicode my `npx` is at version 6.14.8

**Comment by NetOperatorWibby** [comment]
Using 7.5.3 here and `npm` rather than `yarn`.

**Comment by kylemh** [comment]
I use zsh and did not have this issue for reference.

**Comment by typicode** [comment]
Tried today with npm v7.5.4 and `npm exec -- github:typicode/husky-4-to-5 --package-manager npm`. Seems to work.

**Comment by josokinas** [comment]
Forgot to mention I'm using macOS Big Sur - maybe macOS is an issue here?

**Comment by kylemh** [comment]
Using Big Sur + zsh with no issue. Not denying you have an issue, just tryna help isolate the real problem.

**Comment by typicode** [comment]
I had issues with `npx ...` command but it worked with `npm exec -- github:typicode/husky-4-to-5` (npm v7.6.0).

Might be worth giving another try.

Alternatively, if you don't have a lot of repos and/or hooks, you could move your previous config manually. A new command `husky init` have also been introduced to simplify setup.

https://typicode.github.io/husky
