### ISSUE TITLE
Ignores HUSKY_GIT_PARAMS

### ISSUE THREAD

**Issue by Snaptags** [typicode/husky-4-to-5#4]
Thanks for this migration tool, has been really helpful migrating all my hooks!

It did ignore `HUSKY_GIT_PARAMS` though and put the command unmodified into `.husky/pre-commit`

Was an easy fix using the migration FAQ, but the tool should at least warn about it. 

BTW: in my case I had to replace
```
commitlint -E HUSKY_GIT_PARAMS
```
by
```
commitlint --edit $1
```

**Comment by typicode** [comment]
Thanks for the feedback. A warning should be shown (maybe it wasn't apparent enough though)
https://github.com/typicode/husky-4-to-5/blob/main/src/config.ts#L59

**Comment by Snaptags** [comment]
Just ran it again and can confirm the warning to show. Must have missed it due to my terminal color theme :-) Sorry.
