### ISSUE TITLE
Example command for installed binaries fails

### ISSUE THREAD

**Issue by derekschinke** [typicode/husky-4-to-5#5]
After running `npm exec -- github:typicode/husky-4-to-5 --package-manager yarn`, it says this in part of the output:

```
⚠️ pre-commit hook may need to be manually updated to be run via package manager.

Examples:
  jest → npx --no-install jest
       → yarn jest
```

However, `--no-install` fails. The argument has to be `--no` instead.

**Comment by typicode** [comment]
What was the error message?

**Comment by derekschinke** [comment]
Welp, I don't know anymore. I just tried it again and it worked. It potentially could have been an issue with VSCode.
