### ISSUE TITLE
Tool not installing new version

### ISSUE THREAD

**Issue by EndBug** [typicode/husky-4-to-5#7]
Hi, I've run the tool and it didn't upgrade `husky` to v5. It also didn't install `pinst`.
It did the rest fine, I only needed to run the install command for both packages manually. The logs show `npm install --save-dev --quiet husky@5 pinst`, and the next line is `husky install`

**Comment by typicode** [comment]
Thanks for the report.

Not sure why `npm install --save-dev --quiet husky@5 pinst` didn't upgrade your dependencies. Closing as I'm not sure how to reproduce the issue, sorry (tried locally and it worked).

Feel free to re-open if you find out why it's failing :+1:
