### ISSUE TITLE
Missing steps?

### ISSUE THREAD

**Issue by kylemh** [typicode/husky-4-to-5#8]
I feel like this script should

- remove `.huskyrc`
- bump my version in `package.json`

If it can't do these things, the post-install message should describe these as necessary steps. Right?

**Comment by typicode** [comment]
Thanks for the suggestions. The README has been updated so besides removing `.huskyrc` it should do the rest.

Maybe automatic deletion of previous config will be added as a flag later.

**Comment by typicode** [comment]
Just added an option to delete v4 config. It should be complete now :)
